language: php

sudo: true

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4

matrix:
  fast_finish: true

before_script:
  - composer self-update
  - composer install
before_install:
  - rvm install 2.1.5
  - sh -c 'if [ -n "$QMAKE" ]; then sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa && sudo apt-get update && sudo apt-get install libqt5webkit5-dev qtdeclarative5-dev; fi'
  - sh -c 'gem install capybara-webkit -v 1.8.0'

script: xvfb-run ./vendor/bin/kahlan --reporter=verbose
